Overheat: renderer::SphericalCameraController Class Reference
renderer::SphericalCameraController Class Reference
#include <camera_controller.h>
Public Member Functions
SphericalCameraController (std::unique_ptr< ICamera > camera, float radius=1.0f, float phi=0.0f, float theta=0.0f)
void SetPosition (glm::vec3 position) override
void SetRadius (float radius)
void AddRadius (float delta)
float radius () const
void SetLongitude (float phi)
void AddLongitude (float delta)
float phi () const
void SetLatitude (float theta)
void AddLatitude (float delta)
float latitude () const
void SetCamera (std::unique_ptr< ICamera > camera)
const ICamera & camera () const
void SetCameraAspectRatio (float ratio)
void Zoom (float zoom)
Public Member Functions inherited from renderer::SceneObject
SceneObject (glm::vec3 position=consts::init::position, glm::vec3 scale=consts::init::scale, glm::quat rotation=consts::init::rotation)
virtual void SetPosition (glm::vec3 position)
virtual glm::vec3 position () const
virtual void SetScale (glm::vec3 scale)
virtual glm::vec3 scale () const
virtual void SetRotation (glm::quat rotation)
virtual glm::quat rotation () const
virtual glm::mat4 transform () const
glm::vec3 forwardVector () const
glm::vec3 rightVector () const
glm::vec3 upVector () const
virtual float roll () const
virtual float pitch () const
virtual float yaw () const
void Translate (glm::vec3 translation)
void ApplyScale (glm::vec3 scale)
void ApplyScale (float scale)
void Rotate (float angle, glm::vec3 axis)
void Rotate (glm::quat rotation)
void AddRoll (float angle)
void AddPitch (float angle)
void AddYaw (float angle)
Detailed Description
Definition at line 45 of file camera_controller.h.
Constructor & Destructor Documentation
SphericalCameraController()
renderer::SphericalCameraController::SphericalCameraController (std::unique_ptr< ICamera > camera, float radius = 1.0f, float phi = 0.0f, float theta = 0.0f) inline explicit
Definition at line 47 of file camera_controller.h.
Member Function Documentation
AddLatitude()
void renderer::SphericalCameraController::AddLatitude (float delta) inline
Definition at line 71 of file camera_controller.h.
References SetLatitude().
AddLongitude()
void renderer::SphericalCameraController::AddLongitude (float delta) inline
Definition at line 67 of file camera_controller.h.
References SetLongitude().
AddRadius()
void renderer::SphericalCameraController::AddRadius (float delta) inline
Definition at line 63 of file camera_controller.h.
References SetRadius().
camera()
const ICamera & renderer::SphericalCameraController::camera () const inline
Definition at line 77 of file camera_controller.h.
Referenced by SetCamera().
latitude()
float renderer::SphericalCameraController::latitude () const inline
Definition at line 72 of file camera_controller.h.
phi()
float renderer::SphericalCameraController::phi () const inline
Definition at line 68 of file camera_controller.h.
Referenced by SetLongitude().
radius()
float renderer::SphericalCameraController::radius () const inline
Definition at line 64 of file camera_controller.h.
Referenced by SetRadius().
SetCamera()
void renderer::SphericalCameraController::SetCamera (std::unique_ptr< ICamera > camera) inline
Definition at line 74 of file camera_controller.h.
References camera().
SetCameraAspectRatio()
void renderer::SphericalCameraController::SetCameraAspectRatio (float ratio) inline
Definition at line 78 of file camera_controller.h.
SetLatitude()
void renderer::SphericalCameraController::SetLatitude (float theta)
Definition at line 18 of file camera_controller.cpp.
Referenced by AddLatitude().
SetLongitude()
void renderer::SphericalCameraController::SetLongitude (float phi)
Definition at line 10 of file camera_controller.cpp.
References phi().
Referenced by AddLongitude().
SetPosition()
void renderer::SphericalCameraController::SetPosition (glm::vec3 position) inline override virtual
Reimplemented from renderer::SceneObject.
Definition at line 57 of file camera_controller.h.
References renderer::SceneObject::position(), and renderer::SceneObject::SetPosition().
SetRadius()
void renderer::SphericalCameraController::SetRadius (float radius)
Definition at line 5 of file camera_controller.cpp.
References radius().
Referenced by AddRadius().
Zoom()
void renderer::SphericalCameraController::Zoom (float zoom) inline
Definition at line 81 of file camera_controller.h.
References renderer::consts::init::zoom.
The documentation for this class was generated from the following files:
src/renderer/src/camera_controller.h
src/renderer/src/camera_controller.cpp