Overheat: renderer Namespace Reference
renderer Namespace Reference
Namespaces
namespace consts
namespace debug
namespace gl
Classes
class BoundedValue
class GLSceneViewport
class HeatmapMaterial
class ICamera
class IndexBuffer
class IRendererFactory
class ISceneViewport
class OrthographicCamera
class RendererAPI
class Scene
class SceneObject
class SceneShape
class ShaderProgram
class SphericalCameraController
class Texture2D
struct Vec2D
struct Vec3D
struct Vertex
class VertexArray
class VertexBuffer
class VertexBufferLayout
Enumerations
enum class API { None , OpenGL , Vulkan , D3D }
enum class PrimitiveType {
POINTS , LINES , LINE_STRIP , LINE_LOOP ,
TRIANGLES , TRIANGLE_STRIP , TRIANGLE_FAN
}
enum class FilterMode { LINEAR , NEAREST }
enum class WrapMode { CLAMP_TO_EDGE }
Functions
glm::vec3 HighlightTypeToColor (HighlightType highlight_type)
HeatmapMaterial CreateMaterial (const Heatmap &bot_heatmap, const Heatmap &top_heatmap, std::pair< float, float > bounds)
bool CreateShader (const ShaderProgram::Path &source, GLenum shader_type, uint32_t &shader_id)
template<GLenum ptype>
bool GetCompileLinkSuccess (const int32_t id)
template<GLenum ptype>
std::string GetCompileLinkInfoLog (const int32_t id)
template<GLenum ptype, typename... Args>
bool CheckSuccessAndLogError (const int32_t id, fmt::format_string< Args... > msg_template, Args &&... args)
Enumeration Type Documentation
API
enum class renderer::API strong
Enumerator
None
OpenGL
Vulkan
D3D
Definition at line 12 of file i_scene_viewport.h.
FilterMode
enum class renderer::FilterMode strong
Enumerator
LINEAR
NEAREST
Definition at line 5 of file texture2d.h.
PrimitiveType
enum class renderer::PrimitiveType strong
Enumerator
POINTS
LINES
LINE_STRIP
LINE_LOOP
TRIANGLES
TRIANGLE_STRIP
TRIANGLE_FAN
Definition at line 14 of file renderer_api.h.
WrapMode
enum class renderer::WrapMode strong
Enumerator
CLAMP_TO_EDGE
Definition at line 7 of file texture2d.h.
Function Documentation
CheckSuccessAndLogError()
template<GLenum ptype, typename... Args> bool renderer::CheckSuccessAndLogError (const int32_t id, fmt::format_string< Args... > msg_template, Args &&... args)
Definition at line 77 of file shaderprogram.cpp.
CreateMaterial()
HeatmapMaterial renderer::CreateMaterial (const Heatmap & bot_heatmap, const Heatmap & top_heatmap, std::pair< float, float > bounds)
Definition at line 146 of file gl_scene_viewport.cpp.
References renderer::RendererAPI::factory(), Heatmap::max_temp(), Heatmap::min_temp(), Heatmap::temperatures(), and Heatmap::x_resolution().
CreateShader()
bool renderer::CreateShader (const ShaderProgram::Path & source, GLenum shader_type, uint32_t & shader_id)
Definition at line 113 of file shaderprogram.cpp.
Referenced by renderer::ShaderProgram::Load().
GetCompileLinkInfoLog()
template<GLenum ptype> std::string renderer::GetCompileLinkInfoLog (const int32_t id)
Definition at line 64 of file shaderprogram.cpp.
GetCompileLinkSuccess()
template<GLenum ptype> bool renderer::GetCompileLinkSuccess (const int32_t id)
Definition at line 51 of file shaderprogram.cpp.
HighlightTypeToColor()
glm::vec3 renderer::HighlightTypeToColor (HighlightType highlight_type)
Definition at line 92 of file gl_scene_viewport.cpp.
References ActiveSelected, renderer::consts::color_active_selected, renderer::consts::color_not_selected, renderer::consts::color_selected, None, Selected, and renderer::consts::vec3_0.
Referenced by renderer::GLSceneViewport::RenderFrame().