Overheat: renderer::gl::VertexBuffer Class Reference
renderer::gl::VertexBuffer Class Reference
#include <vertexbuffer.h>
Public Member Functions
VertexBuffer ()=delete
VertexBuffer (size_t size)
VertexBuffer (const void *data, size_t size, std::unique_ptr< VertexBufferLayout > &&layout)
VertexBuffer (VertexBuffer &&other) noexcept
VertexBuffer & operator= (VertexBuffer &&other) noexcept
~VertexBuffer ()
VertexBuffer (const VertexBuffer &)=delete
VertexBuffer & operator= (const VertexBuffer &)=delete
void SetLayout (std::unique_ptr< VertexBufferLayout > &&layout) final
const VertexBufferLayout & layout () const final
void Bind () const final
void Unbind () const final
void SetData (const void *data, size_t size, std::unique_ptr< VertexBufferLayout > &&layout) final
Public Member Functions inherited from renderer::VertexBuffer
virtual ~VertexBuffer ()=default
virtual void Bind () const =0
virtual void Unbind () const =0
virtual void SetData (const void *data, size_t size, std::unique_ptr< VertexBufferLayout > &&layout)=0
template<typename T , size_t size>
void SetData (const std::array< T, size > &data, std::unique_ptr< VertexBufferLayout > &&layout)
virtual void SetLayout (std::unique_ptr< VertexBufferLayout > &&layout)=0
virtual const VertexBufferLayout & layout () const =0
Detailed Description
Definition at line 9 of file vertexbuffer.h.
Constructor & Destructor Documentation
VertexBuffer() [1/5]
renderer::gl::VertexBuffer::VertexBuffer () delete
VertexBuffer() [2/5]
renderer::gl::VertexBuffer::VertexBuffer (size_t size) explicit
Definition at line 27 of file vertexbuffer.cpp.
VertexBuffer() [3/5]
renderer::gl::VertexBuffer::VertexBuffer (const void * data, size_t size, std::unique_ptr< VertexBufferLayout > && layout)
Definition at line 30 of file vertexbuffer.cpp.
VertexBuffer() [4/5]
renderer::gl::VertexBuffer::VertexBuffer (VertexBuffer && other) noexcept
Definition at line 38 of file vertexbuffer.cpp.
~VertexBuffer()
renderer::gl::VertexBuffer::~VertexBuffer () virtual
Reimplemented from renderer::VertexBuffer.
Definition at line 34 of file vertexbuffer.cpp.
References renderer::consts::buffer_count_one.
VertexBuffer() [5/5]
renderer::gl::VertexBuffer::VertexBuffer (const VertexBuffer &) delete
Member Function Documentation
Bind()
void renderer::gl::VertexBuffer::Bind () const final virtual
Implements renderer::VertexBuffer.
Definition at line 56 of file vertexbuffer.cpp.
Referenced by SetData().
layout()
const VertexBufferLayout & renderer::gl::VertexBuffer::layout () const inline final virtual
Implements renderer::VertexBuffer.
Definition at line 23 of file vertexbuffer.h.
Referenced by SetData(), and SetLayout().
operator=() [1/2]
VertexBuffer & renderer::gl::VertexBuffer::operator= (const VertexBuffer &) delete
operator=() [2/2]
VertexBuffer & renderer::gl::VertexBuffer::operator= (VertexBuffer && other) noexcept
Definition at line 42 of file vertexbuffer.cpp.
References renderer::consts::buffer_count_one.
SetData()
void renderer::gl::VertexBuffer::SetData (const void * data, size_t size, std::unique_ptr< VertexBufferLayout > && layout) final virtual
Implements renderer::VertexBuffer.
Definition at line 60 of file vertexbuffer.cpp.
References Bind(), and layout().
SetLayout()
void renderer::gl::VertexBuffer::SetLayout (std::unique_ptr< VertexBufferLayout > && layout) inline final virtual
Implements renderer::VertexBuffer.
Definition at line 20 of file vertexbuffer.h.
References layout().
Unbind()
void renderer::gl::VertexBuffer::Unbind () const final virtual
Implements renderer::VertexBuffer.
Definition at line 58 of file vertexbuffer.cpp.
The documentation for this class was generated from the following files:
src/renderer/src/platform/opengl/vertexbuffer.h
src/renderer/src/platform/opengl/vertexbuffer.cpp