Overheat: MainWindow Class Reference
MainWindow Class Reference final
#include <mainwindow.h>
Public Slots
void OnLoadFile3DBtnPressed ()
void OnLoadFile2DBtnPressed ()
void OnShapesSelected (const GlobalShapeIds &shape_ids)
void OnShowMetadata (GlobalId id)
Public Member Functions
MainWindow (QWidget *parent=nullptr)
~MainWindow () override
void LoadFile (std::string trm_file_path, std::string t2d_file_path, GeometryType type)
Detailed Description
Definition at line 18 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr) explicit
Definition at line 10 of file mainwindow.cpp.
References ShapeListWidget::ChangeVisibility(), RendererWidget::OnChangeVisibility(), OnLoadFile2DBtnPressed(), OnLoadFile3DBtnPressed(), OnShapesSelected(), OnShowMetadata(), RendererWidget::onVisualizationOptionsChanged(), ShapeListWidget::ShapesSelected(), ShapeListWidget::ShowMetadata(), and VisualizationOptionsWidget::VisualizationOptionsChanged().
~MainWindow()
MainWindow::~MainWindow () override default
Member Function Documentation
LoadFile()
void MainWindow::LoadFile (std::string trm_file_path, std::string t2d_file_path, GeometryType type)
Definition at line 52 of file mainwindow.cpp.
References ShapeListWidget::AddData(), Core::GetRepresentation(), FileRepresentation::GetShapes(), Core::LoadRepresentation(), LOG_INFO, LOG_WARN, and VisualizationOptionsWidget::SetMinMaxTemp().
OnLoadFile2DBtnPressed
void MainWindow::OnLoadFile2DBtnPressed () slot
Definition at line 83 of file mainwindow.cpp.
References D2.
Referenced by MainWindow().
OnLoadFile3DBtnPressed
void MainWindow::OnLoadFile3DBtnPressed () slot
Definition at line 79 of file mainwindow.cpp.
References D3.
Referenced by MainWindow().
OnShapesSelected
void MainWindow::OnShapesSelected (const GlobalShapeIds & shape_ids) slot
Definition at line 109 of file mainwindow.cpp.
References ActiveSelected, RendererWidget::OnClearSelection(), RendererWidget::OnSetSelection(), OnShowMetadata(), and Selected.
Referenced by MainWindow().
OnShowMetadata
void MainWindow::OnShowMetadata (GlobalId id) slot
Definition at line 131 of file mainwindow.cpp.
References MetadataWidget::ShowMetadata().
Referenced by MainWindow(), and OnShapesSelected().
The documentation for this class was generated from the following files:
src/ui/src/mainwindow.h
src/ui/src/mainwindow.cpp