Overheat: renderer::IRendererFactory Class Reference
renderer::IRendererFactory Class Reference abstract
#include <i_renderer_factory.h>
Public Member Functions
virtual ~IRendererFactory ()=default
virtual std::unique_ptr< IndexBuffer > NewIndexBuffer (const uint32_t *data, size_t size)=0
template<size_t size>
std::unique_ptr< IndexBuffer > NewIndexBuffer (const std::array< uint32_t, size > &data)
virtual std::unique_ptr< VertexArray > NewVertexArray ()=0
virtual std::unique_ptr< VertexArray > NewVertexArray (std::unique_ptr< VertexBuffer > &&vb, std::unique_ptr< IndexBuffer > &&ib)=0
virtual std::unique_ptr< VertexBuffer > NewVertexBuffer (size_t size)=0
virtual std::unique_ptr< VertexBuffer > NewVertexBuffer (const void *data, size_t size, std::unique_ptr< VertexBufferLayout > &&layout)=0
template<typename T , size_t size>
std::unique_ptr< VertexBuffer > NewVertexBuffer (const std::array< T, size > &data, std::unique_ptr< VertexBufferLayout > &&layout)
virtual std::unique_ptr< Texture2D > NewTexture2D (int width, int height, const void *data, int channels=4, FilterMode filter=FilterMode::LINEAR, WrapMode wrap_mode=WrapMode::CLAMP_TO_EDGE, bool generate_bitmap=false)=0
Detailed Description
Definition at line 12 of file i_renderer_factory.h.
Constructor & Destructor Documentation
~IRendererFactory()
virtual renderer::IRendererFactory::~IRendererFactory () virtual default
Member Function Documentation
NewIndexBuffer() [1/2]
template<size_t size> std::unique_ptr< IndexBuffer > renderer::IRendererFactory::NewIndexBuffer (const std::array< uint32_t, size > & data) inline
Definition at line 18 of file i_renderer_factory.h.
References NewIndexBuffer().
NewIndexBuffer() [2/2]
virtual std::unique_ptr< IndexBuffer > renderer::IRendererFactory::NewIndexBuffer (const uint32_t * data, size_t size) pure virtual
Referenced by NewIndexBuffer().
NewTexture2D()
virtual std::unique_ptr< Texture2D > renderer::IRendererFactory::NewTexture2D (int width, int height, const void * data, int channels = 4, FilterMode filter = FilterMode::LINEAR, WrapMode wrap_mode = WrapMode::CLAMP_TO_EDGE, bool generate_bitmap = false) pure virtual
NewVertexArray() [1/2]
virtual std::unique_ptr< VertexArray > renderer::IRendererFactory::NewVertexArray () pure virtual
NewVertexArray() [2/2]
virtual std::unique_ptr< VertexArray > renderer::IRendererFactory::NewVertexArray (std::unique_ptr< VertexBuffer > && vb, std::unique_ptr< IndexBuffer > && ib) pure virtual
NewVertexBuffer() [1/3]
template<typename T , size_t size> std::unique_ptr< VertexBuffer > renderer::IRendererFactory::NewVertexBuffer (const std::array< T, size > & data, std::unique_ptr< VertexBufferLayout > && layout) inline
Definition at line 36 of file i_renderer_factory.h.
References NewVertexBuffer().
NewVertexBuffer() [2/3]
virtual std::unique_ptr< VertexBuffer > renderer::IRendererFactory::NewVertexBuffer (const void * data, size_t size, std::unique_ptr< VertexBufferLayout > && layout) pure virtual
NewVertexBuffer() [3/3]
virtual std::unique_ptr< VertexBuffer > renderer::IRendererFactory::NewVertexBuffer (size_t size) pure virtual
Referenced by renderer::debug::Axes::Axes(), and NewVertexBuffer().
The documentation for this class was generated from the following file:
src/renderer/src/renderer/i_renderer_factory.h