Overheat: SerializableVec< T > Class Template Reference
SerializableVec< T > Class Template Reference
#include <common.h>
Public Member Functions
SerializableVec ()=default
SerializableVec & set_size (const size_t size)
const std::vector< T > & data () const
Friends
std::istream & operator>> (std::istream &in, SerializableVec &vec)
Detailed Description
template<typename T>
class SerializableVec< T >
Definition at line 9 of file common.h.
Constructor & Destructor Documentation
SerializableVec()
template<typename T > SerializableVec< T >::SerializableVec () default
Member Function Documentation
data()
template<typename T > const std::vector< T > & SerializableVec< T >::data () const inline
Definition at line 27 of file common.h.
Referenced by Solver3d_T2D::net_x(), Solver3d_T2D::net_y(), Solver2d_T2D::temperatures(), and Solver3d_T2D::temperatures().
set_size()
template<typename T > SerializableVec & SerializableVec< T >::set_size (const size_t size) inline
Definition at line 13 of file common.h.
Referenced by Readers::Solver2d::LayerType::set_size(), and Spheres::Spheres().
Friends And Related Function Documentation
operator>>
template<typename T > std::istream & operator>> (std::istream & in, SerializableVec< T > & vec) friend
Definition at line 19 of file common.h.
The documentation for this class was generated from the following file:
src/readers/src/common.h