Overheat: ShapeListWidget Class Reference
ShapeListWidget Class Reference
#include <shape_list_widget.h>
Signals
void ShowMetadata (GlobalId id)
void ChangeVisibility (GlobalIds shape_ids, bool is_visivle)
void ShapesSelected (GlobalIds shape_ids)
Public Member Functions
ShapeListWidget (QWidget *parent=nullptr)
void AddData (const InstanceList &data)
void ClearData (const GlobalId &id)
void ClearAll ()
Detailed Description
Definition at line 17 of file shape_list_widget.h.
Constructor & Destructor Documentation
ShapeListWidget()
ShapeListWidget::ShapeListWidget (QWidget * parent = nullptr) explicit
Definition at line 11 of file shape_list_widget.cpp.
Member Function Documentation
AddData()
void ShapeListWidget::AddData (const InstanceList & data) inline
Definition at line 22 of file shape_list_widget.h.
References AddData().
Referenced by AddData(), and MainWindow::LoadFile().
ChangeVisibility
void ShapeListWidget::ChangeVisibility (GlobalIds shape_ids, bool is_visivle) signal
Referenced by MainWindow::MainWindow().
ClearAll()
void ShapeListWidget::ClearAll ()
Definition at line 33 of file shape_list_widget.cpp.
ClearData()
void ShapeListWidget::ClearData (const GlobalId & id)
Definition at line 29 of file shape_list_widget.cpp.
ShapesSelected
void ShapeListWidget::ShapesSelected (GlobalIds shape_ids) signal
Referenced by MainWindow::MainWindow().
ShowMetadata
void ShapeListWidget::ShowMetadata (GlobalId id) signal
Referenced by MainWindow::MainWindow().
The documentation for this class was generated from the following files:
src/ui/src/shape_list_widget.h
src/ui/src/shape_list_widget.cpp