Overheat: VisualizationOptionsWidget Class Reference
VisualizationOptionsWidget Class Reference
#include <visualization_options.h>
Signals
void VisualizationOptionsChanged (const VisualizationOptions &visualization_options)
Public Member Functions
VisualizationOptionsWidget (QWidget *parent=nullptr)
~VisualizationOptionsWidget () override
void SetMinMaxTemp (float min, float max)
Detailed Description
Definition at line 26 of file visualization_options.h.
Constructor & Destructor Documentation
VisualizationOptionsWidget()
VisualizationOptionsWidget::VisualizationOptionsWidget (QWidget * parent = nullptr) explicit
Definition at line 12 of file visualization_options.cpp.
References color, VisualizationOptions::max_temp_color, VisualizationOptions::min_temp_color, SetMinMaxTemp(), VisualizationOptions::stratified_step_, and VisualizationOptionsChanged().
~VisualizationOptionsWidget()
VisualizationOptionsWidget::~VisualizationOptionsWidget () override default
Member Function Documentation
SetMinMaxTemp()
void VisualizationOptionsWidget::SetMinMaxTemp (float min, float max)
Definition at line 112 of file visualization_options.cpp.
Referenced by MainWindow::LoadFile(), and VisualizationOptionsWidget().
VisualizationOptionsChanged
void VisualizationOptionsWidget::VisualizationOptionsChanged (const VisualizationOptions & visualization_options) signal
Referenced by MainWindow::MainWindow(), and VisualizationOptionsWidget().
The documentation for this class was generated from the following files:
src/ui/src/visualization_options.h
src/ui/src/visualization_options.cpp