Overheat: renderer::OrthographicCamera Class Reference
renderer::OrthographicCamera Class Reference
#include <orthographic_camera.h>
Public Member Functions
OrthographicCamera ()=default
OrthographicCamera (float aspect_ratio, float zoom, std::pair< float, float > depth_bounds={0.0f, 1.0f})
OrthographicCamera (float left, float right, float bottom, float top, float near=0.0f, float far=1.0f)
void SetPosition (glm::vec3 position) override
void SetRotation (glm::quat rotation) override
void LookAt (glm::vec3 point_to_view) override
void Zoom (float delta) override
float zoom_level () const override
void SetAspectRatio (float ratio) override
float aspect_ratio () const override
void SetProjection (float left, float right, float bottom, float top, float near=0.0f, float far=1.0f)
const glm::mat4 & viewMatrix () const override
const glm::mat4 & projectionMatrix () const override
const glm::mat4 & viewProjectionMatrix () const override
Public Member Functions inherited from renderer::ICamera
void SetScale (glm::vec3) final
glm::mat4 transform () const override
virtual void LookAt (glm::vec3 point_to_view)=0
virtual void Zoom (float delta)=0
virtual float zoom_level () const =0
virtual void SetAspectRatio (float ratio)=0
virtual float aspect_ratio () const =0
virtual const glm::mat4 & viewMatrix () const =0
virtual const glm::mat4 & projectionMatrix () const =0
virtual const glm::mat4 & viewProjectionMatrix () const =0
Public Member Functions inherited from renderer::SceneObject
SceneObject (glm::vec3 position=consts::init::position, glm::vec3 scale=consts::init::scale, glm::quat rotation=consts::init::rotation)
virtual void SetPosition (glm::vec3 position)
virtual glm::vec3 position () const
virtual void SetScale (glm::vec3 scale)
virtual glm::vec3 scale () const
virtual void SetRotation (glm::quat rotation)
virtual glm::quat rotation () const
virtual glm::mat4 transform () const
glm::vec3 forwardVector () const
glm::vec3 rightVector () const
glm::vec3 upVector () const
virtual float roll () const
virtual float pitch () const
virtual float yaw () const
void Translate (glm::vec3 translation)
void ApplyScale (glm::vec3 scale)
void ApplyScale (float scale)
void Rotate (float angle, glm::vec3 axis)
void Rotate (glm::quat rotation)
void AddRoll (float angle)
void AddPitch (float angle)
void AddYaw (float angle)
Detailed Description
Definition at line 11 of file orthographic_camera.h.
Constructor & Destructor Documentation
OrthographicCamera() [1/3]
renderer::OrthographicCamera::OrthographicCamera () default
OrthographicCamera() [2/3]
renderer::OrthographicCamera::OrthographicCamera (float aspect_ratio, float zoom, std::pair< float, float > depth_bounds = {0.0f, 1.0f})
Definition at line 14 of file orthographic_camera.cpp.
OrthographicCamera() [3/3]
renderer::OrthographicCamera::OrthographicCamera (float left, float right, float bottom, float top, float near = 0.0f, float far = 1.0f)
Definition at line 27 of file orthographic_camera.cpp.
Member Function Documentation
aspect_ratio()
float renderer::OrthographicCamera::aspect_ratio () const inline override virtual
Implements renderer::ICamera.
Definition at line 25 of file orthographic_camera.h.
LookAt()
void renderer::OrthographicCamera::LookAt (glm::vec3 point_to_view) override virtual
Implements renderer::ICamera.
Definition at line 59 of file orthographic_camera.cpp.
References renderer::SceneObject::position(), SetRotation(), and renderer::consts::vec3_z.
projectionMatrix()
const glm::mat4 & renderer::OrthographicCamera::projectionMatrix () const inline override virtual
Implements renderer::ICamera.
Definition at line 32 of file orthographic_camera.h.
SetAspectRatio()
void renderer::OrthographicCamera::SetAspectRatio (float ratio) override virtual
Implements renderer::ICamera.
Definition at line 79 of file orthographic_camera.cpp.
SetPosition()
void renderer::OrthographicCamera::SetPosition (glm::vec3 position) override virtual
Reimplemented from renderer::SceneObject.
Definition at line 64 of file orthographic_camera.cpp.
References renderer::SceneObject::position(), and renderer::SceneObject::SetPosition().
SetProjection()
void renderer::OrthographicCamera::SetProjection (float left, float right, float bottom, float top, float near = 0.0f, float far = 1.0f)
Definition at line 36 of file orthographic_camera.cpp.
SetRotation()
void renderer::OrthographicCamera::SetRotation (glm::quat rotation) override virtual
Reimplemented from renderer::SceneObject.
Definition at line 69 of file orthographic_camera.cpp.
References renderer::SceneObject::rotation(), and renderer::SceneObject::SetRotation().
Referenced by LookAt().
viewMatrix()
const glm::mat4 & renderer::OrthographicCamera::viewMatrix () const inline override virtual
Implements renderer::ICamera.
Definition at line 29 of file orthographic_camera.h.
viewProjectionMatrix()
const glm::mat4 & renderer::OrthographicCamera::viewProjectionMatrix () const inline override virtual
Implements renderer::ICamera.
Definition at line 35 of file orthographic_camera.h.
Zoom()
void renderer::OrthographicCamera::Zoom (float delta) override virtual
Implements renderer::ICamera.
Definition at line 74 of file orthographic_camera.cpp.
zoom_level()
float renderer::OrthographicCamera::zoom_level () const inline override virtual
Implements renderer::ICamera.
Definition at line 23 of file orthographic_camera.h.
The documentation for this class was generated from the following files:
src/renderer/src/renderer/orthographic_camera.h
src/renderer/src/renderer/orthographic_camera.cpp