Overheat: FileRepresentation Class Reference
FileRepresentation Class Reference
#include <databases.h>
Public Types
using Layers = std::vector< Layer >
using Shapes = GeomStorage< BasicShape >::Shapes
Public Member Functions
FileRepresentation (GeomStorage< BasicShape > geom_storage_mv, HeatmapStorage heatmap_storage_mv)
FileRepresentation (FileRepresentation &&)=default
~FileRepresentation ()=default
FileRepresentation (const FileRepresentation &)=delete
FileRepresentation & operator= (const FileRepresentation &)=delete
FileRepresentation & operator= (FileRepresentation &&)=delete
const Shapes & GetShapes (const Box3D &area=Box3D()) const
MetadataPack GetMetadata (GlobalId id) const
Box3D representation_borders () const
GlobalId id () const
std::string RepresentationName () const
GeomStorage< BasicShape > & geom_storage ()
HeatmapStorage & heatmaps ()
InstanceList GetInstanceList () const
void InitLayers ()
Detailed Description
Definition at line 97 of file databases.h.
Member Typedef Documentation
Layers
using FileRepresentation::Layers = std::vector<Layer>
Definition at line 99 of file databases.h.
Shapes
using FileRepresentation::Shapes = GeomStorage<BasicShape>::Shapes
Definition at line 100 of file databases.h.
Constructor & Destructor Documentation
FileRepresentation() [1/3]
FileRepresentation::FileRepresentation (GeomStorage< BasicShape > geom_storage_mv, HeatmapStorage heatmap_storage_mv) inline
Definition at line 101 of file databases.h.
FileRepresentation() [2/3]
FileRepresentation::FileRepresentation (FileRepresentation &&) default
~FileRepresentation()
FileRepresentation::~FileRepresentation () default
FileRepresentation() [3/3]
FileRepresentation::FileRepresentation (const FileRepresentation &) delete
Member Function Documentation
geom_storage()
GeomStorage< BasicShape > & FileRepresentation::geom_storage () inline
Definition at line 123 of file databases.h.
GetInstanceList()
InstanceList FileRepresentation::GetInstanceList () const
Definition at line 78 of file databases.cpp.
References InstanceList::dependants, InstanceList::name, and RepresentationName().
Referenced by Core::GetRepresentationData().
GetMetadata()
MetadataPack FileRepresentation::GetMetadata (GlobalId id) const
Definition at line 18 of file databases.cpp.
References Layer, Representation, and Shape.
Referenced by Core::GetMetadata().
GetShapes()
const FileRepresentation::Shapes & FileRepresentation::GetShapes (const Box3D & area = Box3D()) const
Definition at line 13 of file databases.cpp.
References GeomStorage< Shape >::shapes().
Referenced by MainWindow::LoadFile().
heatmaps()
HeatmapStorage & FileRepresentation::heatmaps () inline
Definition at line 124 of file databases.h.
id()
GlobalId FileRepresentation::id () const inline
Definition at line 118 of file databases.h.
InitLayers()
void FileRepresentation::InitLayers ()
Definition at line 51 of file databases.cpp.
References HeatmapStorage::heatmaps(), and Layer.
operator=() [1/2]
FileRepresentation & FileRepresentation::operator= (const FileRepresentation &) delete
operator=() [2/2]
FileRepresentation & FileRepresentation::operator= (FileRepresentation &&) delete
representation_borders()
Box3D FileRepresentation::representation_borders () const inline
Definition at line 115 of file databases.h.
References HeatmapStorage::representation_borders().
RepresentationName()
std::string FileRepresentation::RepresentationName () const inline
Definition at line 119 of file databases.h.
Referenced by GetInstanceList().
The documentation for this class was generated from the following files:
src/core/include/databases.h
src/core/src/databases.cpp