Overheat: Core Class Reference
Core Class Reference
#include <core.h>
Public Types
using Shapes = FileRepresentation::Shapes
Public Member Functions
GlobalId LoadRepresentation (std::string trm_file_path_mv, std::string t2d_file_path_mv, GeometryType type)
FileRepresentation & GetRepresentation (const GlobalId id)
MetadataPack GetMetadata (const GlobalId id) const
InstanceList GetRepresentationData (const size_t representation_id) const
For filling side widgets.
Static Public Member Functions
static Core & instance ()
Detailed Description
Definition at line 13 of file core.h.
Member Typedef Documentation
Shapes
using Core::Shapes = FileRepresentation::Shapes
Definition at line 15 of file core.h.
Member Function Documentation
GetMetadata()
MetadataPack Core::GetMetadata (const GlobalId id) const inline
Definition at line 29 of file core.h.
References FileRepresentation::GetMetadata(), and GetRepresentation().
GetRepresentation()
FileRepresentation & Core::GetRepresentation (const GlobalId id) inline
Definition at line 24 of file core.h.
Referenced by GetMetadata(), GetRepresentationData(), and MainWindow::LoadFile().
GetRepresentationData()
InstanceList Core::GetRepresentationData (const size_t representation_id) const inline
For filling side widgets.
Definition at line 33 of file core.h.
References FileRepresentation::GetInstanceList(), and GetRepresentation().
instance()
static Core & Core::instance () inline static
Definition at line 17 of file core.h.
References instance().
Referenced by instance().
LoadRepresentation()
GlobalId Core::LoadRepresentation (std::string trm_file_path_mv, std::string t2d_file_path_mv, GeometryType type)
Definition at line 9 of file core.cpp.
References D2, D3, IReader::geometry(), and IReader::heatmaps().
Referenced by MainWindow::LoadFile().
The documentation for this class was generated from the following files:
src/core/include/core.h
src/core/src/core.cpp