Overheat: renderer::Scene Class Reference
renderer::Scene Class Reference
#include <scene.h>
Classes
struct SceneImpl
Public Member Functions
Scene ()
Scene (Scene &&other) noexcept=default
Scene & operator= (Scene &&other) noexcept=default
~Scene ()
Scene (const Scene &)=delete
Scene & operator= (Scene &)=delete
void Clear ()
void AddShapes (const Core::Shapes &shapes)
void AddHeatmaps (const HeatmapStorage &heatmaps_storage)
const std::vector< std::shared_ptr< SceneShape > > & shapes () const
std::vector< std::shared_ptr< SceneShape > > & shapes ()
const Heatmaps & heatmaps () const
std::pair< float, float > bounds () const
const std::shared_ptr< SceneShape > & shape_by_id (GlobalId id) const
std::shared_ptr< SceneShape > & shape_by_id (GlobalId id)
Detailed Description
Definition at line 13 of file scene.h.
Constructor & Destructor Documentation
Scene() [1/3]
renderer::Scene::Scene ()
Definition at line 24 of file scene.cpp.
Scene() [2/3]
renderer::Scene::Scene (Scene && other) default noexcept
~Scene()
renderer::Scene::~Scene () default
Scene() [3/3]
renderer::Scene::Scene (const Scene &) delete
Member Function Documentation
AddHeatmaps()
void renderer::Scene::AddHeatmaps (const HeatmapStorage & heatmaps_storage)
Definition at line 39 of file scene.cpp.
References HeatmapStorage::heatmaps(), heatmaps(), LOG_TRACE, HeatmapStorage::x_size(), and HeatmapStorage::y_size().
AddShapes()
void renderer::Scene::AddShapes (const Core::Shapes & shapes) inline
Definition at line 23 of file scene.h.
References shapes().
bounds()
std::pair< float, float > renderer::Scene::bounds () const
Definition at line 70 of file scene.cpp.
Clear()
void renderer::Scene::Clear ()
Definition at line 72 of file scene.cpp.
heatmaps()
const Heatmaps & renderer::Scene::heatmaps () const
Definition at line 68 of file scene.cpp.
Referenced by AddHeatmaps().
operator=() [1/2]
Scene & renderer::Scene::operator= (Scene && other) default noexcept
operator=() [2/2]
Scene & renderer::Scene::operator= (Scene &) delete
shape_by_id() [1/2]
std::shared_ptr< SceneShape > & renderer::Scene::shape_by_id (GlobalId id)
Definition at line 80 of file scene.cpp.
References shape_by_id().
shape_by_id() [2/2]
const std::shared_ptr< SceneShape > & renderer::Scene::shape_by_id (GlobalId id) const
Definition at line 77 of file scene.cpp.
Referenced by shape_by_id().
shapes() [1/2]
std::vector< std::shared_ptr< SceneShape > > & renderer::Scene::shapes ()
Definition at line 64 of file scene.cpp.
shapes() [2/2]
const std::vector< std::shared_ptr< SceneShape > > & renderer::Scene::shapes () const
Definition at line 61 of file scene.cpp.
Referenced by AddShapes().
The documentation for this class was generated from the following files:
src/renderer/include/scene.h
src/renderer/src/scene.cpp