Overheat: renderer::ShaderProgram Class Reference
renderer::ShaderProgram Class Reference
#include <shaderprogram.h>
Public Types
using Path = std::filesystem::path
Public Member Functions
ShaderProgram (const Path &vertex_shader_path, const Path &fragment_shader_path)
ShaderProgram (ShaderProgram &&other) noexcept
ShaderProgram & operator= (ShaderProgram &&other) noexcept
~ShaderProgram ()
ShaderProgram (const ShaderProgram &)=delete
ShaderProgram & operator= (const ShaderProgram &)=delete
bool Load (const Path &vertex_shader_path, const Path &fragment_shader_path)
void Use () const
bool isUsing () const
bool isCompiled () const noexcept
void SetInt (const char *name, int32_t value) const
void SetBool (const char *name, bool value) const
void SetFloat (const char *name, float value) const
void SetVec2 (const char *name, glm::vec2 value) const
void SetVec3 (const char *name, glm::vec3 value) const
void SetMat4 (const char *name, const glm::mat4 &value) const
void SetMat2x3 (const char *name, glm::mat2x3 value) const
void SetMat2 (const char *name, glm::mat2 value) const
Static Public Member Functions
static void Unuse ()
Detailed Description
Definition at line 11 of file shaderprogram.h.
Member Typedef Documentation
Path
using renderer::ShaderProgram::Path = std::filesystem::path
Definition at line 13 of file shaderprogram.h.
Constructor & Destructor Documentation
ShaderProgram() [1/3]
renderer::ShaderProgram::ShaderProgram (const Path & vertex_shader_path, const Path & fragment_shader_path)
Definition at line 19 of file shaderprogram.cpp.
References Load().
ShaderProgram() [2/3]
renderer::ShaderProgram::ShaderProgram (ShaderProgram && other) noexcept
Definition at line 32 of file shaderprogram.cpp.
~ShaderProgram()
renderer::ShaderProgram::~ShaderProgram ()
Definition at line 25 of file shaderprogram.cpp.
References isUsing(), and Unuse().
ShaderProgram() [3/3]
renderer::ShaderProgram::ShaderProgram (const ShaderProgram &) delete
Member Function Documentation
isCompiled()
bool renderer::ShaderProgram::isCompiled () const inline noexcept
Definition at line 26 of file shaderprogram.h.
isUsing()
bool renderer::ShaderProgram::isUsing () const inline
Definition at line 25 of file shaderprogram.h.
Referenced by ~ShaderProgram().
Load()
bool renderer::ShaderProgram::Load (const Path & vertex_shader_path, const Path & fragment_shader_path)
Definition at line 92 of file shaderprogram.cpp.
References renderer::CreateShader().
Referenced by ShaderProgram().
operator=() [1/2]
ShaderProgram & renderer::ShaderProgram::operator= (const ShaderProgram &) delete
operator=() [2/2]
ShaderProgram & renderer::ShaderProgram::operator= (ShaderProgram && other) noexcept
Definition at line 36 of file shaderprogram.cpp.
SetBool()
void renderer::ShaderProgram::SetBool (const char * name, bool value) const
Definition at line 146 of file shaderprogram.cpp.
SetFloat()
void renderer::ShaderProgram::SetFloat (const char * name, float value) const
Definition at line 149 of file shaderprogram.cpp.
SetInt()
void renderer::ShaderProgram::SetInt (const char * name, int32_t value) const
Definition at line 143 of file shaderprogram.cpp.
SetMat2()
void renderer::ShaderProgram::SetMat2 (const char * name, glm::mat2 value) const
Definition at line 166 of file shaderprogram.cpp.
SetMat2x3()
void renderer::ShaderProgram::SetMat2x3 (const char * name, glm::mat2x3 value) const
Definition at line 162 of file shaderprogram.cpp.
SetMat4()
void renderer::ShaderProgram::SetMat4 (const char * name, const glm::mat4 & value) const
Definition at line 158 of file shaderprogram.cpp.
SetVec2()
void renderer::ShaderProgram::SetVec2 (const char * name, glm::vec2 value) const
Definition at line 152 of file shaderprogram.cpp.
SetVec3()
void renderer::ShaderProgram::SetVec3 (const char * name, glm::vec3 value) const
Definition at line 155 of file shaderprogram.cpp.
Unuse()
void renderer::ShaderProgram::Unuse () static
Definition at line 180 of file shaderprogram.cpp.
Referenced by ~ShaderProgram().
Use()
void renderer::ShaderProgram::Use () const
Definition at line 171 of file shaderprogram.cpp.
The documentation for this class was generated from the following files:
src/renderer/src/renderer/shaderprogram.h
src/renderer/src/renderer/shaderprogram.cpp