Overheat: renderer::RendererAPI Class Reference
renderer::RendererAPI Class Reference abstract
#include <renderer_api.h>
Public Member Functions
virtual ~RendererAPI ()=default
virtual void SetViewPort (uint32_t x, uint32_t y, uint32_t w, uint32_t h)=0
virtual void SetClearColor (glm::vec4 color)=0
virtual void Clear ()=0
void DrawIndexed (const VertexArray &va, const IndexBuffer &ib, PrimitiveType draw_as=PrimitiveType::TRIANGLES) const
void DrawIndexed (const VertexArray &va, PrimitiveType draw_as=PrimitiveType::TRIANGLES) const
Static Public Member Functions
static RendererAPI & Init (API api)
static RendererAPI & instance ()
static API api ()
static IRendererFactory & factory ()
Protected Member Functions
virtual void DrawIndexedImpl (const VertexArray &va, const IndexBuffer &ib, PrimitiveType draw_as) const =0
virtual void InitImpl ()=0
Detailed Description
Definition at line 24 of file renderer_api.h.
Constructor & Destructor Documentation
~RendererAPI()
virtual renderer::RendererAPI::~RendererAPI () virtual default
Member Function Documentation
api()
API renderer::RendererAPI::api () static
Definition at line 44 of file renderer_api.cpp.
Referenced by Init().
Clear()
virtual void renderer::RendererAPI::Clear () pure virtual
Implemented in renderer::gl::RendererAPI.
DrawIndexed() [1/2]
void renderer::RendererAPI::DrawIndexed (const VertexArray & va, const IndexBuffer & ib, PrimitiveType draw_as = PrimitiveType::TRIANGLES) const inline
Definition at line 34 of file renderer_api.h.
References DrawIndexedImpl().
DrawIndexed() [2/2]
void renderer::RendererAPI::DrawIndexed (const VertexArray & va, PrimitiveType draw_as = PrimitiveType::TRIANGLES) const inline
Definition at line 39 of file renderer_api.h.
References DrawIndexedImpl(), and renderer::VertexArray::indexBuffer().
DrawIndexedImpl()
virtual void renderer::RendererAPI::DrawIndexedImpl (const VertexArray & va, const IndexBuffer & ib, PrimitiveType draw_as) const protected pure virtual
Referenced by DrawIndexed().
factory()
IRendererFactory & renderer::RendererAPI::factory () static
Definition at line 51 of file renderer_api.cpp.
Referenced by renderer::debug::Axes::Axes(), renderer::CreateMaterial(), and renderer::SceneShape::SceneShape().
Init()
RendererAPI & renderer::RendererAPI::Init (API api) static
Definition at line 33 of file renderer_api.cpp.
References api(), and instance().
InitImpl()
virtual void renderer::RendererAPI::InitImpl () protected pure virtual
Implemented in renderer::gl::RendererAPI.
instance()
RendererAPI & renderer::RendererAPI::instance () static
Definition at line 46 of file renderer_api.cpp.
Referenced by renderer::debug::Axes::Axes(), Init(), renderer::GLSceneViewport::RenderFrame(), and renderer::GLSceneViewport::Resize().
SetClearColor()
virtual void renderer::RendererAPI::SetClearColor (glm::vec4 color) pure virtual
Implemented in renderer::gl::RendererAPI.
SetViewPort()
virtual void renderer::RendererAPI::SetViewPort (uint32_t x, uint32_t y, uint32_t w, uint32_t h) pure virtual
Implemented in renderer::gl::RendererAPI.
Referenced by renderer::GLSceneViewport::Resize().
The documentation for this class was generated from the following files:
src/renderer/src/renderer/renderer_api.h
src/renderer/src/renderer/renderer_api.cpp