Overheat: Config Class Reference
Config Class Reference
#include <config.h>
Public Types
using Path = std::filesystem::path
Public Member Functions
Path executable_path () const
Path executable_dir_path () const
Static Public Member Functions
static void Init (Path executable_path)
static const Config & instance ()
Detailed Description
Definition at line 9 of file config.h.
Member Typedef Documentation
Path
using Config::Path = std::filesystem::path
Definition at line 11 of file config.h.
Member Function Documentation
executable_dir_path()
Path Config::executable_dir_path () const inline
Definition at line 21 of file config.h.
executable_path()
Path Config::executable_path () const inline
Definition at line 20 of file config.h.
Referenced by Init().
Init()
static void Config::Init (Path executable_path) inline static
Definition at line 12 of file config.h.
References executable_path().
Referenced by main().
instance()
static const Config & Config::instance () inline static
Definition at line 18 of file config.h.
The documentation for this class was generated from the following file:
src/common/include/config.h