Overheat: RendererWidget Class Reference
RendererWidget Class Reference
#include <renderer_widget.h>
Public Slots
void onVisualizationOptionsChanged (const VisualizationOptions &visualization_options)
Public Member Functions
RendererWidget (QWidget *parent=nullptr)
RendererWidget (QWidget *parent, const std::shared_ptr< renderer::Scene > &scene)
~RendererWidget () override
void UpdateVisualizationOptions (const VisualizationOptions &visualization_options)
void initializeGL () override
void paintGL () override
void resizeGL (int w, int h) override
void mousePressEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void OnChangeVisibility (GlobalIds shape_ids, bool is_visible)
void OnSetSelection (GlobalIds shape_ids, HighlightType type)
void OnClearSelection ()
Detailed Description
Definition at line 12 of file renderer_widget.h.
Constructor & Destructor Documentation
RendererWidget() [1/2]
RendererWidget::RendererWidget (QWidget * parent = nullptr) explicit
Definition at line 22 of file renderer_widget.cpp.
RendererWidget() [2/2]
RendererWidget::RendererWidget (QWidget * parent, const std::shared_ptr< renderer::Scene > & scene)
Definition at line 11 of file renderer_widget.cpp.
References surface_format().
~RendererWidget()
RendererWidget::~RendererWidget () override
Definition at line 25 of file renderer_widget.cpp.
Member Function Documentation
initializeGL()
void RendererWidget::initializeGL () override
Definition at line 36 of file renderer_widget.cpp.
References renderer::ISceneViewport::Create(), and renderer::OpenGL.
mouseDoubleClickEvent()
void RendererWidget::mouseDoubleClickEvent (QMouseEvent * event) override
Definition at line 139 of file renderer_widget.cpp.
mouseMoveEvent()
void RendererWidget::mouseMoveEvent (QMouseEvent * event) override
Definition at line 113 of file renderer_widget.cpp.
References renderer::Vec2D::x.
mousePressEvent()
void RendererWidget::mousePressEvent (QMouseEvent * event) override
Definition at line 106 of file renderer_widget.cpp.
mouseReleaseEvent()
void RendererWidget::mouseReleaseEvent (QMouseEvent * event) override
Definition at line 111 of file renderer_widget.cpp.
OnChangeVisibility()
void RendererWidget::OnChangeVisibility (GlobalIds shape_ids, bool is_visible) inline
Definition at line 41 of file renderer_widget.h.
Referenced by MainWindow::MainWindow().
OnClearSelection()
void RendererWidget::OnClearSelection () inline
Definition at line 47 of file renderer_widget.h.
Referenced by MainWindow::OnShapesSelected().
OnSetSelection()
void RendererWidget::OnSetSelection (GlobalIds shape_ids, HighlightType type) inline
Definition at line 44 of file renderer_widget.h.
Referenced by MainWindow::OnShapesSelected().
onVisualizationOptionsChanged
void RendererWidget::onVisualizationOptionsChanged (const VisualizationOptions & visualization_options) inline slot
Definition at line 37 of file renderer_widget.h.
References UpdateVisualizationOptions().
Referenced by MainWindow::MainWindow().
paintGL()
void RendererWidget::paintGL () override
Definition at line 64 of file renderer_widget.cpp.
resizeGL()
void RendererWidget::resizeGL (int w, int h) override
Definition at line 69 of file renderer_widget.cpp.
UpdateVisualizationOptions()
void RendererWidget::UpdateVisualizationOptions (const VisualizationOptions & visualization_options)
Definition at line 74 of file renderer_widget.cpp.
References VisualizationOptions::draw_mode, VisualizationOptions::max_temp, VisualizationOptions::max_temp_color, VisualizationOptions::min_temp, VisualizationOptions::min_temp_color, and VisualizationOptions::stratified_step_.
Referenced by onVisualizationOptionsChanged().
The documentation for this class was generated from the following files:
src/ui/src/renderer_widget.h
src/ui/src/renderer_widget.cpp