Overheat: Heatmap Class Reference
Heatmap Class Reference
#include <heatmap.h>
Public Member Functions
Heatmap (Floats temperature_mv, size_t x_resolution, size_t y_resolution, const std::ranges::min_max_result< float > &temp_range=min_max_floats)
std::span< const float > row (size_t i) const
std::span< float > row (size_t i)
const Floats & temperatures () const
size_t x_resolution () const
size_t y_resolution () const
float min_temp () const
float max_temp () const
void DebugPrint (size_t step=1) const
Detailed Description
Definition at line 10 of file heatmap.h.
Constructor & Destructor Documentation
Heatmap()
Heatmap::Heatmap (Floats temperature_mv, size_t x_resolution, size_t y_resolution, const std::ranges::min_max_result< float > & temp_range = min_max_floats) explicit
Definition at line 5 of file heatmap.cpp.
Member Function Documentation
DebugPrint()
void Heatmap::DebugPrint (size_t step = 1) const
Definition at line 22 of file heatmap.cpp.
References LOG_DEBUG, and row().
max_temp()
float Heatmap::max_temp () const inline
Definition at line 26 of file heatmap.h.
Referenced by HeatmapNormalizer::BilinearInterpolate(), renderer::CreateMaterial(), and HeatmapNormalizer::Normalize().
min_temp()
float Heatmap::min_temp () const inline
Definition at line 25 of file heatmap.h.
Referenced by HeatmapNormalizer::BilinearInterpolate(), renderer::CreateMaterial(), and HeatmapNormalizer::Normalize().
row() [1/2]
std::span< float > Heatmap::row (size_t i) inline
Definition at line 19 of file heatmap.h.
row() [2/2]
std::span< const float > Heatmap::row (size_t i) const inline
Definition at line 16 of file heatmap.h.
Referenced by HeatmapNormalizer::BilinearInterpolate(), DebugPrint(), HeatmapNormalizer::FindBilinearInterpolationCell(), and HeatmapNormalizer::Normalize().
temperatures()
const Floats & Heatmap::temperatures () const inline
Definition at line 22 of file heatmap.h.
Referenced by renderer::CreateMaterial().
x_resolution()
size_t Heatmap::x_resolution () const inline
Definition at line 23 of file heatmap.h.
Referenced by HeatmapNormalizer::BilinearInterpolate(), and renderer::CreateMaterial().
y_resolution()
size_t Heatmap::y_resolution () const inline
Definition at line 24 of file heatmap.h.
Referenced by HeatmapNormalizer::BilinearInterpolate(), and HeatmapNormalizer::Normalize().
The documentation for this class was generated from the following files:
src/core/include/heatmap.h
src/core/src/heatmap.cpp