Overheat: renderer::SceneObject Class Reference
renderer::SceneObject Class Reference
#include <scene_object.h>
Public Member Functions
SceneObject (glm::vec3 position=consts::init::position, glm::vec3 scale=consts::init::scale, glm::quat rotation=consts::init::rotation)
virtual void SetPosition (glm::vec3 position)
virtual glm::vec3 position () const
virtual void SetScale (glm::vec3 scale)
virtual glm::vec3 scale () const
virtual void SetRotation (glm::quat rotation)
virtual glm::quat rotation () const
virtual glm::mat4 transform () const
glm::vec3 forwardVector () const
glm::vec3 rightVector () const
glm::vec3 upVector () const
virtual float roll () const
virtual float pitch () const
virtual float yaw () const
void Translate (glm::vec3 translation)
void ApplyScale (glm::vec3 scale)
void ApplyScale (float scale)
void Rotate (float angle, glm::vec3 axis)
void Rotate (glm::quat rotation)
void AddRoll (float angle)
void AddPitch (float angle)
void AddYaw (float angle)
Detailed Description
Definition at line 9 of file scene_object.h.
Constructor & Destructor Documentation
SceneObject()
renderer::SceneObject::SceneObject (glm::vec3 position = consts::init::position, glm::vec3 scale = consts::init::scale, glm::quat rotation = consts::init::rotation) inline explicit
Definition at line 11 of file scene_object.h.
Member Function Documentation
AddPitch()
void renderer::SceneObject::AddPitch (float angle) inline
Definition at line 61 of file scene_object.h.
References Rotate(), and renderer::consts::vec4_y_v.
AddRoll()
void renderer::SceneObject::AddRoll (float angle) inline
Definition at line 60 of file scene_object.h.
References Rotate(), and renderer::consts::vec4_x_v.
AddYaw()
void renderer::SceneObject::AddYaw (float angle) inline
Definition at line 62 of file scene_object.h.
References Rotate(), and renderer::consts::vec4_z_v.
ApplyScale() [1/2]
void renderer::SceneObject::ApplyScale (float scale) inline
Definition at line 53 of file scene_object.h.
References scale(), and SetScale().
ApplyScale() [2/2]
void renderer::SceneObject::ApplyScale (glm::vec3 scale) inline
Definition at line 52 of file scene_object.h.
References scale(), and SetScale().
forwardVector()
glm::vec3 renderer::SceneObject::forwardVector () const inline
Definition at line 29 of file scene_object.h.
References rotation(), and renderer::consts::vec3_z.
pitch()
virtual float renderer::SceneObject::pitch () const inline virtual
Definition at line 41 of file scene_object.h.
position()
virtual glm::vec3 renderer::SceneObject::position () const inline virtual
Definition at line 18 of file scene_object.h.
Referenced by renderer::OrthographicCamera::LookAt(), SetPosition(), renderer::SphericalCameraController::SetPosition(), renderer::OrthographicCamera::SetPosition(), and renderer::ICamera::transform().
rightVector()
glm::vec3 renderer::SceneObject::rightVector () const inline
Definition at line 32 of file scene_object.h.
References rotation(), and renderer::consts::vec3_x.
roll()
virtual float renderer::SceneObject::roll () const inline virtual
Definition at line 38 of file scene_object.h.
Rotate() [1/2]
void renderer::SceneObject::Rotate (float angle, glm::vec3 axis) inline
Definition at line 54 of file scene_object.h.
References rotation(), and SetRotation().
Referenced by AddPitch(), AddRoll(), AddYaw(), and Rotate().
Rotate() [2/2]
void renderer::SceneObject::Rotate (glm::quat rotation) inline
Definition at line 57 of file scene_object.h.
References Rotate(), and rotation().
rotation()
virtual glm::quat renderer::SceneObject::rotation () const inline virtual
Definition at line 22 of file scene_object.h.
Referenced by forwardVector(), rightVector(), Rotate(), SetRotation(), renderer::OrthographicCamera::SetRotation(), transform(), renderer::ICamera::transform(), and upVector().
scale()
virtual glm::vec3 renderer::SceneObject::scale () const inline virtual
Definition at line 20 of file scene_object.h.
Referenced by ApplyScale(), and SetScale().
SetPosition()
virtual void renderer::SceneObject::SetPosition (glm::vec3 position) inline virtual
Reimplemented in renderer::SphericalCameraController, and renderer::OrthographicCamera.
Definition at line 17 of file scene_object.h.
References position().
Referenced by renderer::SphericalCameraController::SetPosition(), renderer::OrthographicCamera::SetPosition(), and Translate().
SetRotation()
virtual void renderer::SceneObject::SetRotation (glm::quat rotation) inline virtual
Reimplemented in renderer::OrthographicCamera.
Definition at line 21 of file scene_object.h.
References rotation().
Referenced by Rotate(), and renderer::OrthographicCamera::SetRotation().
SetScale()
virtual void renderer::SceneObject::SetScale (glm::vec3 scale) inline virtual
Reimplemented in renderer::ICamera.
Definition at line 19 of file scene_object.h.
References scale().
Referenced by ApplyScale().
transform()
virtual glm::mat4 renderer::SceneObject::transform () const inline virtual
Reimplemented in renderer::ICamera.
Definition at line 23 of file scene_object.h.
References rotation(), and renderer::consts::init::scale.
Translate()
void renderer::SceneObject::Translate (glm::vec3 translation) inline
Definition at line 49 of file scene_object.h.
References SetPosition().
upVector()
glm::vec3 renderer::SceneObject::upVector () const inline
Definition at line 35 of file scene_object.h.
References rotation(), and renderer::consts::vec3_y.
yaw()
virtual float renderer::SceneObject::yaw () const inline virtual
Definition at line 44 of file scene_object.h.
The documentation for this class was generated from the following file:
src/renderer/src/renderer/scene_object.h