Overheat: renderer::GLSceneViewport Class Reference
renderer::GLSceneViewport Class Reference final
#include <gl_scene_viewport.h>
Classes
struct Impl
Public Member Functions
GLSceneViewport (std::shared_ptr< Scene > scene)
~GLSceneViewport () override
void Initialize (int w, int h) override
void SetColorRange (Color min, Color max) override
void SetTemperatureRange (float min, float max) override
void RenderFrame () override
void ClearResources () override
void Resize (int w, int h) override
void MoveCamera (Vec2D screenPoint, Vec2D delta) override
void RotateCamera (Vec2D screenPoint, Vec2D delta) override
void ZoomView (float delta) override
void SetVisibility (const GlobalIds &to_change, bool is_visible) override
void SetDrawMode (DrawMode mode) override
void SetStratifiedStep (float step) override
void ClearSelection () override
void SetSelection (const GlobalIds &to_change, HighlightType type) override
Public Member Functions inherited from renderer::ISceneViewport
virtual ~ISceneViewport ()=default
virtual void Initialize (int w, int h)=0
virtual void ClearResources ()=0
virtual void RenderFrame ()=0
virtual void Resize (int w, int h)=0
virtual void MoveCamera (Vec2D screenPoint, Vec2D delta)=0
virtual void RotateCamera (Vec2D screenPoint, Vec2D delta)=0
virtual void ZoomView (float delta)=0
virtual void SetTemperatureRange (float min, float max)=0
void SetTemperatureRange (TemperatureRange temps)
virtual void SetColorRange (Color min, Color max)=0
void SetColorRange (ColorRange colors)
void SetMinMaxTemperatureAndColorRanges (TemperatureRange temperatures, ColorRange colors)
virtual void SetDrawMode (DrawMode mode)=0
virtual void SetStratifiedStep (float step)=0
virtual void SetVisibility (const GlobalIds &to_change, bool is_visible)=0
virtual void ClearSelection ()=0
virtual void SetSelection (const GlobalIds &to_change, HighlightType type)=0
bool is_initialized () const
Additional Inherited Members
Public Types inherited from renderer::ISceneViewport
using TemperatureRange = std::pair< float, float >
using Color = std::array< float, 3 >
using ColorRange = std::pair< Color, Color >
Static Public Member Functions inherited from renderer::ISceneViewport
static std::unique_ptr< ISceneViewport > Create (API api, std::shared_ptr< Scene > scene)
Protected Attributes inherited from renderer::ISceneViewport
bool is_initialized_ = false
Detailed Description
Definition at line 14 of file gl_scene_viewport.h.
Constructor & Destructor Documentation
GLSceneViewport()
renderer::GLSceneViewport::GLSceneViewport (std::shared_ptr< Scene > scene) explicit
Definition at line 40 of file gl_scene_viewport.cpp.
~GLSceneViewport()
renderer::GLSceneViewport::~GLSceneViewport () override
Definition at line 43 of file gl_scene_viewport.cpp.
Member Function Documentation
ClearResources()
void renderer::GLSceneViewport::ClearResources () override virtual
Implements renderer::ISceneViewport.
Definition at line 90 of file gl_scene_viewport.cpp.
ClearSelection()
void renderer::GLSceneViewport::ClearSelection () override virtual
Implements renderer::ISceneViewport.
Definition at line 283 of file gl_scene_viewport.cpp.
Initialize()
void renderer::GLSceneViewport::Initialize (int w, int h) override virtual
Implements renderer::ISceneViewport.
Definition at line 45 of file gl_scene_viewport.cpp.
References renderer::ISceneViewport::is_initialized_.
MoveCamera()
void renderer::GLSceneViewport::MoveCamera (Vec2D screenPoint, Vec2D delta) override virtual
Implements renderer::ISceneViewport.
Definition at line 212 of file gl_scene_viewport.cpp.
References renderer::Vec2D::x, and renderer::Vec2D::y.
RenderFrame()
void renderer::GLSceneViewport::RenderFrame () override virtual
Implements renderer::ISceneViewport.
Definition at line 114 of file gl_scene_viewport.cpp.
References renderer::HighlightTypeToColor(), renderer::RendererAPI::instance(), renderer::LINES, None, and renderer::ICamera::viewProjectionMatrix().
Resize()
void renderer::GLSceneViewport::Resize (int w, int h) override virtual
Implements renderer::ISceneViewport.
Definition at line 190 of file gl_scene_viewport.cpp.
References renderer::RendererAPI::instance(), and renderer::RendererAPI::SetViewPort().
RotateCamera()
void renderer::GLSceneViewport::RotateCamera (Vec2D screenPoint, Vec2D delta) override virtual
Implements renderer::ISceneViewport.
Definition at line 231 of file gl_scene_viewport.cpp.
References renderer::Vec2D::x, and renderer::Vec2D::y.
SetColorRange()
void renderer::GLSceneViewport::SetColorRange (const ISceneViewport::Color min, const ISceneViewport::Color max) override virtual
Implements renderer::ISceneViewport.
Definition at line 203 of file gl_scene_viewport.cpp.
SetDrawMode()
void renderer::GLSceneViewport::SetDrawMode (DrawMode mode) override virtual
Implements renderer::ISceneViewport.
Definition at line 261 of file gl_scene_viewport.cpp.
References Gradient, and Stratified.
SetSelection()
void renderer::GLSceneViewport::SetSelection (const GlobalIds & to_change, HighlightType type) override virtual
Implements renderer::ISceneViewport.
Definition at line 289 of file gl_scene_viewport.cpp.
SetStratifiedStep()
void renderer::GLSceneViewport::SetStratifiedStep (float step) override virtual
Implements renderer::ISceneViewport.
Definition at line 276 of file gl_scene_viewport.cpp.
SetTemperatureRange()
void renderer::GLSceneViewport::SetTemperatureRange (float min, float max) override virtual
Implements renderer::ISceneViewport.
Definition at line 196 of file gl_scene_viewport.cpp.
SetVisibility()
void renderer::GLSceneViewport::SetVisibility (const GlobalIds & to_change, bool is_visible) override virtual
Implements renderer::ISceneViewport.
Definition at line 254 of file gl_scene_viewport.cpp.
ZoomView()
void renderer::GLSceneViewport::ZoomView (float delta) override virtual
Implements renderer::ISceneViewport.
Definition at line 246 of file gl_scene_viewport.cpp.
References renderer::consts::init::zoom.
The documentation for this class was generated from the following files:
src/renderer/src/gl_scene_viewport.h
src/renderer/src/gl_scene_viewport.cpp