Overheat: MetadataStorage< Data > Class Template Reference
MetadataStorage< Data > Class Template Reference
#include <metadata_storage.h>
Public Member Functions
MetadataPack GetData (const GlobalId global_id) const
MetadataPack GetData (InstanceID instance_id) const
template<typename T , class... Args>
void AddData (InstanceID instance_id, std::string &&description, T &&data, Args &&... args)
std::string GetInstanceName (const GlobalId global_id) const
MetadataStorage ()=default
~MetadataStorage ()=default
Detailed Description
template<class... Data>
class MetadataStorage< Data >
Definition at line 16 of file metadata_storage.h.
Constructor & Destructor Documentation
MetadataStorage()
template<class... Data> MetadataStorage< Data >::MetadataStorage () default
~MetadataStorage()
template<class... Data> MetadataStorage< Data >::~MetadataStorage () default
Member Function Documentation
AddData()
template<class... Data> template<typename T , class... Args> void MetadataStorage< Data >::AddData (InstanceID instance_id, std::string && description, T && data, Args &&... args) inline
Definition at line 46 of file metadata_storage.h.
References MetadataStorage< Data >::AddData().
Referenced by MetadataStorage< Data >::AddData().
GetData() [1/2]
template<class... Data> MetadataPack MetadataStorage< Data >::GetData (const GlobalId global_id) const inline
Definition at line 41 of file metadata_storage.h.
References MetadataStorage< Data >::GetData(), GlobalId::id(), and GlobalId::type().
Referenced by MetadataStorage< Data >::GetData().
GetData() [2/2]
template<class... Data> MetadataPack MetadataStorage< Data >::GetData (InstanceID instance_id) const
Definition at line 119 of file metadata_storage.h.
GetInstanceName()
template<class... Data> std::string MetadataStorage< Data >::GetInstanceName (const GlobalId global_id) const inline
Definition at line 53 of file metadata_storage.h.
References GlobalId::id(), Layer, Representation, Shape, and GlobalId::type().
The documentation for this class was generated from the following file:
src/core/include/metadata_storage.h