Overheat: GeomStorage< Shape > Class Template Reference
GeomStorage< Shape > Class Template Reference
#include <databases.h>
Public Types
using ShapePtr = std::shared_ptr< Shape >
using Shapes = std::vector< ShapePtr >
Public Member Functions
GeomStorage ()=default
void AddShape (ShapePtr shape)
const Shapes & shapes () const
const ShapePtr shape (ShapeId id) const
const ShapePtr operator[] (ShapeId id) const
void Clear ()
Detailed Description
template<class Shape>
class GeomStorage< Shape >
Definition at line 12 of file databases.h.
Member Typedef Documentation
ShapePtr
template<class Shape > using GeomStorage< Shape >::ShapePtr = std::shared_ptr<Shape>
Definition at line 14 of file databases.h.
Shapes
template<class Shape > using GeomStorage< Shape >::Shapes = std::vector<ShapePtr>
Definition at line 15 of file databases.h.
Constructor & Destructor Documentation
GeomStorage()
template<class Shape > GeomStorage< Shape >::GeomStorage () default
Member Function Documentation
AddShape()
template<class Shape > void GeomStorage< Shape >::AddShape (ShapePtr shape) inline
Definition at line 17 of file databases.h.
References GeomStorage< Shape >::shape().
Referenced by Readers::Solver3d::HPU::geometry(), Readers::Solver3d::BS::geometry(), and Readers::Solver3d::D::geometry().
Clear()
template<class Shape > void GeomStorage< Shape >::Clear () inline
Definition at line 24 of file databases.h.
operator[]()
template<class Shape > const ShapePtr GeomStorage< Shape >::operator[] (ShapeId id) const inline
Definition at line 23 of file databases.h.
References GeomStorage< Shape >::shape().
shape()
template<class Shape > const ShapePtr GeomStorage< Shape >::shape (ShapeId id) const inline
Definition at line 19 of file databases.h.
Referenced by GeomStorage< Shape >::AddShape(), and GeomStorage< Shape >::operator[]().
shapes()
template<class Shape > const Shapes & GeomStorage< Shape >::shapes () const inline
Definition at line 18 of file databases.h.
Referenced by FileRepresentation::GetShapes().
The documentation for this class was generated from the following file:
src/core/include/databases.h