Overheat: src/ui/src/renderer_widget.cpp File Reference
renderer_widget.cpp File Reference
#include "renderer_widget.h"
#include <qsurfaceformat.h>
#include <QOpenGLContext>
#include "i_scene_viewport.h"
#include "log.h"
Functions
QSurfaceFormat surface_format (QSurfaceFormat::FormatOptions options={})
Function Documentation
surface_format()
QSurfaceFormat surface_format (QSurfaceFormat::FormatOptions options = {})
Definition at line 91 of file renderer_widget.cpp.
References surface_format().
Referenced by RendererWidget::RendererWidget(), and surface_format().