Overheat: renderer::ICamera Class Reference
renderer::ICamera Class Reference abstract
#include <i_camera.h>
Public Member Functions
void SetScale (glm::vec3) final
glm::mat4 transform () const override
virtual void LookAt (glm::vec3 point_to_view)=0
virtual void Zoom (float delta)=0
virtual float zoom_level () const =0
virtual void SetAspectRatio (float ratio)=0
virtual float aspect_ratio () const =0
virtual const glm::mat4 & viewMatrix () const =0
virtual const glm::mat4 & projectionMatrix () const =0
virtual const glm::mat4 & viewProjectionMatrix () const =0
Public Member Functions inherited from renderer::SceneObject
SceneObject (glm::vec3 position=consts::init::position, glm::vec3 scale=consts::init::scale, glm::quat rotation=consts::init::rotation)
virtual void SetPosition (glm::vec3 position)
virtual glm::vec3 position () const
virtual void SetScale (glm::vec3 scale)
virtual glm::vec3 scale () const
virtual void SetRotation (glm::quat rotation)
virtual glm::quat rotation () const
virtual glm::mat4 transform () const
glm::vec3 forwardVector () const
glm::vec3 rightVector () const
glm::vec3 upVector () const
virtual float roll () const
virtual float pitch () const
virtual float yaw () const
void Translate (glm::vec3 translation)
void ApplyScale (glm::vec3 scale)
void ApplyScale (float scale)
void Rotate (float angle, glm::vec3 axis)
void Rotate (glm::quat rotation)
void AddRoll (float angle)
void AddPitch (float angle)
void AddYaw (float angle)
Detailed Description
Definition at line 10 of file i_camera.h.
Member Function Documentation
aspect_ratio()
virtual float renderer::ICamera::aspect_ratio () const pure virtual
Implemented in renderer::OrthographicCamera.
LookAt()
virtual void renderer::ICamera::LookAt (glm::vec3 point_to_view) pure virtual
Implemented in renderer::OrthographicCamera.
projectionMatrix()
virtual const glm::mat4 & renderer::ICamera::projectionMatrix () const pure virtual
Implemented in renderer::OrthographicCamera.
SetAspectRatio()
virtual void renderer::ICamera::SetAspectRatio (float ratio) pure virtual
Implemented in renderer::OrthographicCamera.
SetScale()
void renderer::ICamera::SetScale (glm::vec3) inline final virtual
Reimplemented from renderer::SceneObject.
Definition at line 12 of file i_camera.h.
transform()
glm::mat4 renderer::ICamera::transform () const inline override virtual
Reimplemented from renderer::SceneObject.
Definition at line 14 of file i_camera.h.
References renderer::SceneObject::position(), and renderer::SceneObject::rotation().
viewMatrix()
virtual const glm::mat4 & renderer::ICamera::viewMatrix () const pure virtual
Implemented in renderer::OrthographicCamera.
viewProjectionMatrix()
virtual const glm::mat4 & renderer::ICamera::viewProjectionMatrix () const pure virtual
Implemented in renderer::OrthographicCamera.
Referenced by renderer::GLSceneViewport::RenderFrame().
Zoom()
virtual void renderer::ICamera::Zoom (float delta) pure virtual
Implemented in renderer::OrthographicCamera.
zoom_level()
virtual float renderer::ICamera::zoom_level () const pure virtual
Implemented in renderer::OrthographicCamera.
The documentation for this class was generated from the following file:
src/renderer/src/renderer/i_camera.h