Overheat: renderer::gl::IndexBuffer Class Reference
renderer::gl::IndexBuffer Class Reference final
#include <indexbuffer.h>
Public Member Functions
IndexBuffer (const uint32_t *data, size_t count)
template<size_t size>
IndexBuffer (const std::array< uint32_t, size > &data)
IndexBuffer (IndexBuffer &&other) noexcept
IndexBuffer & operator= (IndexBuffer &&other) noexcept
~IndexBuffer () override
IndexBuffer ()=delete
IndexBuffer (const IndexBuffer &)=delete
IndexBuffer & operator= (const IndexBuffer &)=delete
void Bind () const final
void Unbind () const final
uint32_t elements_count () const final
virtual ~IndexBuffer ()=default
virtual void Bind () const =0
virtual void Unbind () const =0
virtual uint32_t elements_count () const =0
Detailed Description
Definition at line 9 of file indexbuffer.h.
Constructor & Destructor Documentation
IndexBuffer() [1/5]
renderer::gl::IndexBuffer::IndexBuffer (const uint32_t * data, size_t count)
Definition at line 9 of file indexbuffer.cpp.
References Bind(), and renderer::consts::buffer_count_one.
IndexBuffer() [2/5]
template<size_t size> renderer::gl::IndexBuffer::IndexBuffer (const std::array< uint32_t, size > & data) inline explicit
Definition at line 13 of file indexbuffer.h.
IndexBuffer() [3/5]
renderer::gl::IndexBuffer::IndexBuffer (IndexBuffer && other) noexcept
Definition at line 19 of file indexbuffer.cpp.
~IndexBuffer()
renderer::gl::IndexBuffer::~IndexBuffer () override virtual
Reimplemented from renderer::IndexBuffer.
Definition at line 17 of file indexbuffer.cpp.
References renderer::consts::buffer_count_one.
IndexBuffer() [4/5]
renderer::gl::IndexBuffer::IndexBuffer () delete
IndexBuffer() [5/5]
renderer::gl::IndexBuffer::IndexBuffer (const IndexBuffer &) delete
Member Function Documentation
Bind()
void renderer::gl::IndexBuffer::Bind () const final virtual
Implements renderer::IndexBuffer.
Definition at line 37 of file indexbuffer.cpp.
Referenced by IndexBuffer().
elements_count()
uint32_t renderer::gl::IndexBuffer::elements_count () const inline final virtual
Implements renderer::IndexBuffer.
Definition at line 23 of file indexbuffer.h.
Referenced by renderer::gl::RendererAPI::DrawIndexedImpl().
operator=() [1/2]
IndexBuffer & renderer::gl::IndexBuffer::operator= (const IndexBuffer &) delete
operator=() [2/2]
IndexBuffer & renderer::gl::IndexBuffer::operator= (IndexBuffer && other) noexcept
Definition at line 23 of file indexbuffer.cpp.
References renderer::consts::buffer_count_one.
Unbind()
void renderer::gl::IndexBuffer::Unbind () const final virtual
Implements renderer::IndexBuffer.
Definition at line 39 of file indexbuffer.cpp.
The documentation for this class was generated from the following files:
src/renderer/src/platform/opengl/indexbuffer.h
src/renderer/src/platform/opengl/indexbuffer.cpp