Overheat: HeatmapNormalizer Class Reference
HeatmapNormalizer Class Reference
#include <heatmap_normalizer.h>
Classes
struct Cell
Public Types
using FloatPair = std::pair< float, float >
using SizeTPair = std::pair< size_t, size_t >
Public Member Functions
HeatmapNormalizer (const HeatmapStorage &heatmap_storage, size_t max_resolution)
Heatmap BilinearInterpolate (const Heatmap &heatmap)
Heatmap BilinearInterpolateSlow (const Heatmap &heatmap)
void Normalize (Heatmap &heatmap)
size_t FindOptimalResolution (float min_old_step, float max_dimension_size, size_t max_resolution)
Finds minimal resolution, that would be a power of 2 and all cells would be less than min_old_step.
Static Public Member Functions
static Cell FindBilinearInterpolationCell (const Heatmap &heatmap, const Floats &x_coords, const Floats &y_coords, FloatPair search_coords, float env_temp)
static float Lerp (std::pair< float, float > bound_coords, std::pair< float, float > values, float interpolation_coord)
Linear interpolation by coordinates.
static size_t CalculateBatchSize (float right_coord, float start_coord, float step_size)
Computes amount of possible interpolation result from start_coord to right_coord with given step_size including the first coordinate.
template<typename OutputIt >
static OutputIt BatchLerp (std::pair< float, float > bound_coords, std::pair< float, float > values, float start_coord, float step_size, OutputIt d_first)
Interpolates several values in current bounds by bounds coordinates, starting coordinate and step size. Written with inspiration from STL.
template<typename OutputIt >
static OutputIt InterpolateRow (std::span< const float > row, const Floats &steps, float step_size, OutputIt d_first)
Interpolates row with raw values, with each row[i] and row[i+1] values separated by steps[i].
Detailed Description
Definition at line 12 of file heatmap_normalizer.h.
Member Typedef Documentation
FloatPair
using HeatmapNormalizer::FloatPair = std::pair<float, float>
Definition at line 16 of file heatmap_normalizer.h.
SizeTPair
using HeatmapNormalizer::SizeTPair = std::pair<size_t, size_t>
Definition at line 17 of file heatmap_normalizer.h.
Constructor & Destructor Documentation
HeatmapNormalizer()
HeatmapNormalizer::HeatmapNormalizer (const HeatmapStorage & heatmap_storage, size_t max_resolution)
Definition at line 20 of file heatmap_normalizer.cpp.
Member Function Documentation
BatchLerp()
template<typename OutputIt > OutputIt HeatmapNormalizer::BatchLerp (std::pair< float, float > bound_coords, std::pair< float, float > values, float start_coord, float step_size, OutputIt d_first) static
Interpolates several values in current bounds by bounds coordinates, starting coordinate and step size. Written with inspiration from STL.
Template Parameters
OutputIt - must meet the requirements of LegacyOutputIterator.
Parameters
bound_coords - pair of the interpolation values coordinates. Requires bound_coords.first < bound_coords.second
interpolating_values - pair of the actual interpolating values
start_coord - first coordinate of the interpolation result
step_size - distance between interpolation result
d_first - the beginning of the destination range
Returns
OutputIt - Output iterator to the element past the last interpolation result
Definition at line 130 of file heatmap_normalizer.h.
References CalculateBatchSize(), Lerp(), and LOG_TRACE.
Referenced by InterpolateRow().
BilinearInterpolate()
Heatmap HeatmapNormalizer::BilinearInterpolate (const Heatmap & heatmap)
Definition at line 108 of file heatmap_normalizer.cpp.
References InterpolateRow(), Lerp(), LOG_DEBUG, LOG_TRACE, Heatmap::max_temp(), Heatmap::min_temp(), Heatmap::row(), Heatmap::x_resolution(), and Heatmap::y_resolution().
BilinearInterpolateSlow()
Heatmap HeatmapNormalizer::BilinearInterpolateSlow (const Heatmap & heatmap)
Definition at line 34 of file heatmap_normalizer.cpp.
References FindBilinearInterpolationCell(), and Lerp().
CalculateBatchSize()
size_t HeatmapNormalizer::CalculateBatchSize (float right_coord, float start_coord, float step_size) static
Computes amount of possible interpolation result from start_coord to right_coord with given step_size including the first coordinate.
Parameters
right_coord - interpolation right bound
start_coord - the first coordinate of the interpolation results
step_size - distance between interpolation results
Returns
size_t -
Definition at line 222 of file heatmap_normalizer.cpp.
Referenced by BatchLerp(), and InterpolateRow().
FindBilinearInterpolationCell()
HeatmapNormalizer::Cell HeatmapNormalizer::FindBilinearInterpolationCell (const Heatmap & heatmap, const Floats & x_coords, const Floats & y_coords, FloatPair search_coords, float env_temp) static
Definition at line 62 of file heatmap_normalizer.cpp.
References Heatmap::row().
Referenced by BilinearInterpolateSlow().
FindOptimalResolution()
size_t HeatmapNormalizer::FindOptimalResolution (float min_old_step, float max_dimension_size, size_t max_resolution)
Finds minimal resolution, that would be a power of 2 and all cells would be less than min_old_step.
Parameters
min_old_step - minimal node step in the heatmap
max_dimension_size - maximal resolution of the either dimesion of the heatmap
max_resolution - limit for the final resolution
Returns
size_t
Definition at line 184 of file heatmap_normalizer.cpp.
InterpolateRow()
template<typename OutputIt > OutputIt HeatmapNormalizer::InterpolateRow (std::span< const float > row, const Floats & steps, float step_size, OutputIt d_first) static
Interpolates row with raw values, with each row[i] and row[i+1] values separated by steps[i].
Interpolating performs with BatchLerp for each pair of values.
Template Parameters
OutputIt - must meet the requirements of LegacyOutputIterator.
Parameters
row - values for interpolation
steps - distances between row values
step_size - distance between interpolation results
d_first - the beginning of the destination range
Returns
OutputIt - Output iterator to the element past the last interpolation result
Definition at line 152 of file heatmap_normalizer.h.
References BatchLerp(), and CalculateBatchSize().
Referenced by BilinearInterpolate().
Lerp()
float HeatmapNormalizer::Lerp (std::pair< float, float > bound_coords, std::pair< float, float > values, float interpolation_coord) static
Linear interpolation by coordinates.
Parameters
bound_coords - value coordinates for interpolation
values - values itself for interpolation
interpolation_coord - coordinate, where compute interpolation result
Returns
float - interpolation result
Definition at line 206 of file heatmap_normalizer.cpp.
Referenced by BatchLerp(), BilinearInterpolate(), and BilinearInterpolateSlow().
Normalize()
void HeatmapNormalizer::Normalize (Heatmap & heatmap)
Definition at line 173 of file heatmap_normalizer.cpp.
References Heatmap::max_temp(), Heatmap::min_temp(), Heatmap::row(), and Heatmap::y_resolution().
The documentation for this class was generated from the following files:
src/core/include/heatmap_normalizer.h
src/core/src/heatmap_normalizer.cpp