Overheat: renderer::SceneShape Class Reference
renderer::SceneShape Class Reference
#include <scene_shape.h>
Public Member Functions
SceneShape (const BasicShape &shape)
const BasicShape & core_shape () const
const VertexArray & vertex_array () const
GlobalId id () const
LayerId layer_id () const
void SetIsVisible (bool is_visible)
bool is_visible () const
void SetHighlightType (HighlightType highlight_type)
HighlightType highlight_type () const
Public Member Functions inherited from renderer::SceneObject
SceneObject (glm::vec3 position=consts::init::position, glm::vec3 scale=consts::init::scale, glm::quat rotation=consts::init::rotation)
virtual void SetPosition (glm::vec3 position)
virtual glm::vec3 position () const
virtual void SetScale (glm::vec3 scale)
virtual glm::vec3 scale () const
virtual void SetRotation (glm::quat rotation)
virtual glm::quat rotation () const
virtual glm::mat4 transform () const
glm::vec3 forwardVector () const
glm::vec3 rightVector () const
glm::vec3 upVector () const
virtual float roll () const
virtual float pitch () const
virtual float yaw () const
void Translate (glm::vec3 translation)
void ApplyScale (glm::vec3 scale)
void ApplyScale (float scale)
void Rotate (float angle, glm::vec3 axis)
void Rotate (glm::quat rotation)
void AddRoll (float angle)
void AddPitch (float angle)
void AddYaw (float angle)
Detailed Description
Definition at line 12 of file scene_shape.h.
Constructor & Destructor Documentation
SceneShape()
renderer::SceneShape::SceneShape (const BasicShape & shape) explicit
Definition at line 31 of file scene_shape.cpp.
References BasicShape::bbox(), Box< dim >::coordinates(), and renderer::RendererAPI::factory().
Member Function Documentation
core_shape()
const BasicShape & renderer::SceneShape::core_shape () const inline
Definition at line 15 of file scene_shape.h.
highlight_type()
HighlightType renderer::SceneShape::highlight_type () const inline
Definition at line 26 of file scene_shape.h.
Referenced by SetHighlightType().
id()
GlobalId renderer::SceneShape::id () const inline
Definition at line 19 of file scene_shape.h.
References BasicShape::id().
is_visible()
bool renderer::SceneShape::is_visible () const inline
Definition at line 22 of file scene_shape.h.
Referenced by SetIsVisible().
layer_id()
LayerId renderer::SceneShape::layer_id () const inline
Definition at line 20 of file scene_shape.h.
References BasicShape::layer_id().
SetHighlightType()
void renderer::SceneShape::SetHighlightType (HighlightType highlight_type) inline
Definition at line 23 of file scene_shape.h.
References highlight_type().
SetIsVisible()
void renderer::SceneShape::SetIsVisible (bool is_visible) inline
Definition at line 21 of file scene_shape.h.
References is_visible().
vertex_array()
const VertexArray & renderer::SceneShape::vertex_array () const inline
Definition at line 18 of file scene_shape.h.
The documentation for this class was generated from the following files:
src/renderer/src/application/scene_shape.h
src/renderer/src/application/scene_shape.cpp