Overheat: HeatmapStorage Class Reference
HeatmapStorage Class Reference
#include <databases.h>
Public Member Functions
HeatmapStorage ()=default
HeatmapStorage (std::vector< float > x_steps, std::vector< float > y_steps, const std::vector< float > &temperature, float environment_temperature, Box3D representation_borders)
Box3D representation_borders () const
float environment_temperature () const
const Heatmap & operator[] (const size_t id) const
float x_size () const
float y_size () const
float MinStep () const
float max_temp () const
float min_temp () const
const Heatmaps & heatmaps () const
const Floats & x_coords () const
const Floats & y_coords () const
Detailed Description
Definition at line 51 of file databases.h.
Constructor & Destructor Documentation
HeatmapStorage() [1/2]
HeatmapStorage::HeatmapStorage () default
HeatmapStorage() [2/2]
HeatmapStorage::HeatmapStorage (std::vector< float > x_steps, std::vector< float > y_steps, const std::vector< float > & temperature, float environment_temperature, Box3D representation_borders)
Definition at line 94 of file databases.cpp.
References Box< dim >::coordinates(), X, and Y.
Member Function Documentation
environment_temperature()
float HeatmapStorage::environment_temperature () const inline
Definition at line 60 of file databases.h.
heatmaps()
const Heatmaps & HeatmapStorage::heatmaps () const inline
Definition at line 76 of file databases.h.
Referenced by renderer::Scene::AddHeatmaps(), and FileRepresentation::InitLayers().
max_temp()
float HeatmapStorage::max_temp () const
Definition at line 152 of file databases.cpp.
min_temp()
float HeatmapStorage::min_temp () const
Definition at line 158 of file databases.cpp.
MinStep()
float HeatmapStorage::MinStep () const inline
Definition at line 73 of file databases.h.
operator[]()
const Heatmap & HeatmapStorage::operator[] (const size_t id) const inline
Definition at line 63 of file databases.h.
representation_borders()
Box3D HeatmapStorage::representation_borders () const inline
Definition at line 57 of file databases.h.
Referenced by FileRepresentation::representation_borders().
x_coords()
const Floats & HeatmapStorage::x_coords () const inline
Definition at line 77 of file databases.h.
x_size()
float HeatmapStorage::x_size () const inline
Definition at line 67 of file databases.h.
References Box< dim >::coordinates().
Referenced by renderer::Scene::AddHeatmaps().
y_coords()
const Floats & HeatmapStorage::y_coords () const inline
Definition at line 78 of file databases.h.
y_size()
float HeatmapStorage::y_size () const inline
Definition at line 70 of file databases.h.
References Box< dim >::coordinates().
Referenced by renderer::Scene::AddHeatmaps().
The documentation for this class was generated from the following files:
src/core/include/databases.h
src/core/src/databases.cpp