Overheat: renderer::ISceneViewport Class Reference
renderer::ISceneViewport Class Reference abstract
#include <i_scene_viewport.h>
Public Types
using TemperatureRange = std::pair< float, float >
using Color = std::array< float, 3 >
using ColorRange = std::pair< Color, Color >
Public Member Functions
virtual ~ISceneViewport ()=default
virtual void Initialize (int w, int h)=0
virtual void ClearResources ()=0
virtual void RenderFrame ()=0
virtual void Resize (int w, int h)=0
virtual void MoveCamera (Vec2D screenPoint, Vec2D delta)=0
virtual void RotateCamera (Vec2D screenPoint, Vec2D delta)=0
virtual void ZoomView (float delta)=0
virtual void SetTemperatureRange (float min, float max)=0
void SetTemperatureRange (TemperatureRange temps)
virtual void SetColorRange (Color min, Color max)=0
void SetColorRange (ColorRange colors)
void SetMinMaxTemperatureAndColorRanges (TemperatureRange temperatures, ColorRange colors)
virtual void SetDrawMode (DrawMode mode)=0
virtual void SetStratifiedStep (float step)=0
virtual void SetVisibility (const GlobalIds &to_change, bool is_visible)=0
virtual void ClearSelection ()=0
virtual void SetSelection (const GlobalIds &to_change, HighlightType type)=0
bool is_initialized () const
Static Public Member Functions
static std::unique_ptr< ISceneViewport > Create (API api, std::shared_ptr< Scene > scene)
Protected Attributes
bool is_initialized_ = false
Detailed Description
Definition at line 19 of file i_scene_viewport.h.
Member Typedef Documentation
Color
using renderer::ISceneViewport::Color = std::array<float, 3>
Definition at line 22 of file i_scene_viewport.h.
ColorRange
using renderer::ISceneViewport::ColorRange = std::pair<Color, Color>
Definition at line 23 of file i_scene_viewport.h.
TemperatureRange
using renderer::ISceneViewport::TemperatureRange = std::pair<float, float>
Definition at line 21 of file i_scene_viewport.h.
Constructor & Destructor Documentation
~ISceneViewport()
virtual renderer::ISceneViewport::~ISceneViewport () virtual default
Member Function Documentation
ClearResources()
virtual void renderer::ISceneViewport::ClearResources () pure virtual
Implemented in renderer::GLSceneViewport.
ClearSelection()
virtual void renderer::ISceneViewport::ClearSelection () pure virtual
Implemented in renderer::GLSceneViewport.
Create()
std::unique_ptr< ISceneViewport > renderer::ISceneViewport::Create (API api, std::shared_ptr< Scene > scene) static
Definition at line 15 of file i_scene_viewport.cpp.
References CASE_NOT_SUPPORTED, renderer::D3D, LOG_CRITICAL, renderer::None, renderer::OpenGL, and renderer::Vulkan.
Referenced by RendererWidget::initializeGL().
Initialize()
virtual void renderer::ISceneViewport::Initialize (int w, int h) pure virtual
Implemented in renderer::GLSceneViewport.
is_initialized()
bool renderer::ISceneViewport::is_initialized () const inline
Definition at line 66 of file i_scene_viewport.h.
References is_initialized_.
MoveCamera()
virtual void renderer::ISceneViewport::MoveCamera (Vec2D screenPoint, Vec2D delta) pure virtual
Implemented in renderer::GLSceneViewport.
RenderFrame()
virtual void renderer::ISceneViewport::RenderFrame () pure virtual
Implemented in renderer::GLSceneViewport.
Resize()
virtual void renderer::ISceneViewport::Resize (int w, int h) pure virtual
Implemented in renderer::GLSceneViewport.
RotateCamera()
virtual void renderer::ISceneViewport::RotateCamera (Vec2D screenPoint, Vec2D delta) pure virtual
Implemented in renderer::GLSceneViewport.
SetColorRange() [1/2]
virtual void renderer::ISceneViewport::SetColorRange (Color min, Color max) pure virtual
Implemented in renderer::GLSceneViewport.
Referenced by SetColorRange(), and SetMinMaxTemperatureAndColorRanges().
SetColorRange() [2/2]
void renderer::ISceneViewport::SetColorRange (ColorRange colors) inline
Definition at line 53 of file i_scene_viewport.h.
References SetColorRange().
SetDrawMode()
virtual void renderer::ISceneViewport::SetDrawMode (DrawMode mode) pure virtual
Implemented in renderer::GLSceneViewport.
SetMinMaxTemperatureAndColorRanges()
void renderer::ISceneViewport::SetMinMaxTemperatureAndColorRanges (TemperatureRange temperatures, ColorRange colors) inline
Definition at line 56 of file i_scene_viewport.h.
References SetColorRange(), and SetTemperatureRange().
SetSelection()
virtual void renderer::ISceneViewport::SetSelection (const GlobalIds & to_change, HighlightType type) pure virtual
Implemented in renderer::GLSceneViewport.
SetStratifiedStep()
virtual void renderer::ISceneViewport::SetStratifiedStep (float step) pure virtual
Implemented in renderer::GLSceneViewport.
SetTemperatureRange() [1/2]
virtual void renderer::ISceneViewport::SetTemperatureRange (float min, float max) pure virtual
Implemented in renderer::GLSceneViewport.
Referenced by SetMinMaxTemperatureAndColorRanges(), and SetTemperatureRange().
SetTemperatureRange() [2/2]
void renderer::ISceneViewport::SetTemperatureRange (TemperatureRange temps) inline
Definition at line 49 of file i_scene_viewport.h.
References SetTemperatureRange().
SetVisibility()
virtual void renderer::ISceneViewport::SetVisibility (const GlobalIds & to_change, bool is_visible) pure virtual
Implemented in renderer::GLSceneViewport.
ZoomView()
virtual void renderer::ISceneViewport::ZoomView (float delta) pure virtual
Implemented in renderer::GLSceneViewport.
Member Data Documentation
is_initialized_
bool renderer::ISceneViewport::is_initialized_ = false protected
Definition at line 69 of file i_scene_viewport.h.
Referenced by renderer::GLSceneViewport::Initialize(), and is_initialized().
The documentation for this class was generated from the following files:
src/renderer/include/i_scene_viewport.h
src/renderer/src/i_scene_viewport.cpp