Overheat: renderer::VertexBuffer Class Reference
renderer::VertexBuffer Class Reference abstract
#include <vertexbuffer.h>
Public Member Functions
virtual ~VertexBuffer ()=default
virtual void Bind () const =0
virtual void Unbind () const =0
virtual void SetData (const void *data, size_t size, std::unique_ptr< VertexBufferLayout > &&layout)=0
template<typename T , size_t size>
void SetData (const std::array< T, size > &data, std::unique_ptr< VertexBufferLayout > &&layout)
virtual void SetLayout (std::unique_ptr< VertexBufferLayout > &&layout)=0
virtual const VertexBufferLayout & layout () const =0
Detailed Description
Definition at line 10 of file vertexbuffer.h.
Constructor & Destructor Documentation
~VertexBuffer()
virtual renderer::VertexBuffer::~VertexBuffer () virtual default
Reimplemented in renderer::gl::VertexBuffer.
Member Function Documentation
Bind()
virtual void renderer::VertexBuffer::Bind () const pure virtual
Implemented in renderer::gl::VertexBuffer.
layout()
virtual const VertexBufferLayout & renderer::VertexBuffer::layout () const pure virtual
Implemented in renderer::gl::VertexBuffer.
Referenced by SetData().
SetData() [1/2]
template<typename T , size_t size> void renderer::VertexBuffer::SetData (const std::array< T, size > & data, std::unique_ptr< VertexBufferLayout > && layout) inline
Definition at line 18 of file vertexbuffer.h.
References layout(), and SetData().
SetData() [2/2]
virtual void renderer::VertexBuffer::SetData (const void * data, size_t size, std::unique_ptr< VertexBufferLayout > && layout) pure virtual
Implemented in renderer::gl::VertexBuffer.
Referenced by SetData().
SetLayout()
virtual void renderer::VertexBuffer::SetLayout (std::unique_ptr< VertexBufferLayout > && layout) pure virtual
Implemented in renderer::gl::VertexBuffer.
Unbind()
virtual void renderer::VertexBuffer::Unbind () const pure virtual
Implemented in renderer::gl::VertexBuffer.
The documentation for this class was generated from the following file:
src/renderer/src/renderer/vertexbuffer.h