Overheat: GlobalId Class Reference
GlobalId Class Reference
#include <common.h>
Public Types
using InstanceId = size_t
Public Member Functions
GlobalId ()=default
constexpr GlobalId (const InstanceType type, const InstanceId id, const RepresentationId representation_id)
GlobalId (const GlobalId &other)=default
bool operator== (const GlobalId &other) const =default
auto operator<=> (const GlobalId &other) const =default
constexpr InstanceId id () const
constexpr RepresentationId representation_id () const
constexpr InstanceType type () const
Detailed Description
Definition at line 53 of file common.h.
Member Typedef Documentation
InstanceId
using GlobalId::InstanceId = size_t
Definition at line 55 of file common.h.
Constructor & Destructor Documentation
GlobalId() [1/3]
GlobalId::GlobalId () default
GlobalId() [2/3]
constexpr GlobalId::GlobalId (const InstanceType type, const InstanceId id, const RepresentationId representation_id) inline constexpr
Definition at line 57 of file common.h.
GlobalId() [3/3]
GlobalId::GlobalId (const GlobalId & other) default
Member Function Documentation
id()
constexpr InstanceId GlobalId::id () const inline constexpr
Definition at line 69 of file common.h.
Referenced by MetadataStorage< Data >::GetData(), and MetadataStorage< Data >::GetInstanceName().
operator<=>()
auto GlobalId::operator<=> (const GlobalId & other) const default
operator==()
bool GlobalId::operator== (const GlobalId & other) const default
representation_id()
constexpr RepresentationId GlobalId::representation_id () const inline constexpr
Definition at line 72 of file common.h.
type()
constexpr InstanceType GlobalId::type () const inline constexpr
Definition at line 75 of file common.h.
Referenced by MetadataStorage< Data >::GetData(), and MetadataStorage< Data >::GetInstanceName().
The documentation for this class was generated from the following file:
src/common/include/common.h