Overheat: Solver3d_T2D Class Reference
Solver3d_T2D Class Reference
#include <solver3d_T2D.h>
Public Member Functions
Box3D design_borders () const
size_t layers_count () const
const std::vector< float > & net_x () const
const std::vector< float > & net_y () const
const std::vector< float > & temperatures () const
float env_temp () const
Friends
std::istream & operator>> (std::istream &istream, Solver3d_T2D &t2d)
Detailed Description
Definition at line 84 of file solver3d_T2D.h.
Member Function Documentation
design_borders()
Box3D Solver3d_T2D::design_borders () const inline
Definition at line 86 of file solver3d_T2D.h.
References BodySize::x, BodySize::y, and BodySize::z.
env_temp()
float Solver3d_T2D::env_temp () const inline
Definition at line 99 of file solver3d_T2D.h.
layers_count()
size_t Solver3d_T2D::layers_count () const inline
Definition at line 89 of file solver3d_T2D.h.
net_x()
const std::vector< float > & Solver3d_T2D::net_x () const inline
Definition at line 90 of file solver3d_T2D.h.
References SerializableVec< T >::data().
net_y()
const std::vector< float > & Solver3d_T2D::net_y () const inline
Definition at line 93 of file solver3d_T2D.h.
References SerializableVec< T >::data().
temperatures()
const std::vector< float > & Solver3d_T2D::temperatures () const inline
Definition at line 96 of file solver3d_T2D.h.
References SerializableVec< T >::data().
Friends And Related Function Documentation
operator>>
std::istream & operator>> (std::istream & istream, Solver3d_T2D & t2d) friend
Definition at line 100 of file solver3d_T2D.h.
The documentation for this class was generated from the following file:
src/readers/src/solver3d/solver3d_T2D.h