name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  artifact: "Windows.zip"
  builddir: ${{github.workspace}}/build

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{env.builddir}}

    - name: Configure CMake
      shell: bash
      working-directory: ${{env.builddir}}
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{env.builddir}}
      run: cmake --build . --config $BUILD_TYPE --parallel --target ui

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ${{env.artifact}} ${{env.builddir}}/bin

    - uses: actions/upload-artifact@v2
      with:
        name: vendor.zip
